---
title: Jacqueline Yue's site
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jac.oiyana@gmail.com
description: Jacqueline Yue is currently a Product Designer and Manager at BuzzFeed,
  where she design and product lead data and learning tools.
baseurl: ''
url: http://yourdomain.com
twitter_username: oiyana
github_username: oiyana
markdown: kramdown
