# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jacqueline Yue's site
email: jac.oiyana@gmail.com
description: Jacqueline Yue is currently a Product Designer and Manager at BuzzFeed, where she design and product lead data and learning tools.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: oiyana
github_username:  oiyana

# Build settings
markdown: kramdown
